trigger:
  branches:
    include:
      - main
      - develop
      - feature/*
  paths:
    include:
      - 'bicep/*'
      - 'azure-pipelines.yml'

pr:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - 'bicep/*'

variables:
  # Replace with your actual service connection name
  azureServiceConnection: 'azure-service-connection-v2'  # ✅ This looks correct
  subscriptionId: 'db11dea1-6d39-4635-8129-55183eb04293'
  location: 'East US'
  
  # Build variables
  vmImageName: 'ubuntu-latest'
  bicepFile: 'bicep/main.bicep'
  # Using consistent parameter file reference
  parametersFile: 'bicep/main.parameters.json'

stages:
# Always validate first
- stage: Validate
  displayName: 'Validate Bicep Template'
  jobs:
  - job: ValidateBicep
    displayName: 'Validate and What-If Analysis'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureCLI@2
      displayName: 'Install Bicep CLI'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az bicep install
          echo "Bicep version: $(az bicep version)"

    - task: AzureCLI@2
      displayName: 'Lint and Build Bicep'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Linting Bicep template..."
          az bicep build --file $(bicepFile)
          echo "✅ Bicep template is syntactically valid"

    - task: AzureCLI@2
      displayName: 'What-If Analysis (Dev)'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "🔍 Analyzing changes for Development environment..."
          az deployment group what-if \
            --resource-group "rg-myapp-test-v2" \
            --template-file $(bicepFile) \
            --parameters @$(parametersFile) environment=dev \
            --result-format FullResourcePayloads

# Deploy to Development (automatic for develop branch)
- stage: DeployDev
  displayName: '🚀 Deploy to Development'
  dependsOn: Validate
  condition: |
    and(
      succeeded(),
      or(
        eq(variables['Build.SourceBranch'], 'refs/heads/develop'),
        eq(variables['Build.SourceBranch'], 'refs/heads/main')
      )
    )
  variables:
    resourceGroupName: 'rg-myapp-test-v2'  # ✅ Using your actual RG name
    environmentName: 'dev'
  jobs:
  - job: DeployToDev  # ✅ CHANGED: Using regular job instead of deployment
    displayName: 'Deploy to Development'
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
    
    - task: AzureCLI@2
      displayName: 'Deploy to Development'
      inputs:
        azureSubscription: $(azureServiceConnection)  # ✅ Now this will work
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az bicep install
          
          echo "🚀 Deploying to Development environment..."
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file $(bicepFile) \
            --parameters @$(parametersFile) environment=$(environmentName) \
            --name "bicep-$(environmentName)-$(Build.BuildNumber)" \
            --verbose
          
          echo "✅ Development deployment completed"

    - task: AzureCLI@2
      displayName: 'Verify Development Deployment'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "🔍 Verifying deployment..."
          az deployment group show \
            --resource-group $(resourceGroupName) \
            --name "bicep-$(environmentName)-$(Build.BuildNumber)" \
            --query properties.provisioningState
          
          echo "📊 Deployment outputs:"
          az deployment group show \
            --resource-group $(resourceGroupName) \
            --name "bicep-$(environmentName)-$(Build.BuildNumber)" \
            --query properties.outputs

# Deploy to Staging (automatic promotion from dev, only for main branch)
- stage: DeployStaging
  displayName: '🎯 Deploy to Staging'
  dependsOn: DeployDev
  condition: |
    and(
      succeeded(),
      eq(variables['Build.SourceBranch'], 'refs/heads/main')
    )
  variables:
    resourceGroupName: 'rg-myapp-test-v2'  # ✅ Using same RG for testing
    environmentName: 'staging'
  jobs:
  - job: DeployToStaging  # ✅ CHANGED: Using regular job
    displayName: 'Deploy to Staging'
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
    
    - task: AzureCLI@2
      displayName: 'What-If Analysis (Staging)'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az bicep install
          echo "🔍 Analyzing changes for Staging environment..."
          az deployment group what-if \
            --resource-group $(resourceGroupName) \
            --template-file $(bicepFile) \
            --parameters @$(parametersFile) environment=$(environmentName) \
            --result-format FullResourcePayloads

    - task: AzureCLI@2
      displayName: 'Deploy to Staging'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "🎯 Deploying to Staging environment..."
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file $(bicepFile) \
            --parameters @$(parametersFile) environment=$(environmentName) \
            --name "bicep-$(environmentName)-$(Build.BuildNumber)" \
            --verbose
          
          echo "✅ Staging deployment completed"

# Deploy to Production (manual approval required)
- stage: DeployProd
  displayName: '🏭 Deploy to Production'
  dependsOn: DeployStaging
  condition: |
    and(
      succeeded(),
      eq(variables['Build.SourceBranch'], 'refs/heads/main')
    )
  variables:
    resourceGroupName: 'rg-myapp-test-v2'  # ✅ Using same RG for testing
    environmentName: 'prod'
  jobs:
  - job: DeployToProduction  # ✅ CHANGED: Using regular job
    displayName: 'Deploy to Production'
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
    
    - task: AzureCLI@2
      displayName: 'Final What-If Analysis (Production)'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az bicep install
          echo "🔍 Final analysis for Production environment..."
          az deployment group what-if \
            --resource-group $(resourceGroupName) \
            --template-file $(bicepFile) \
            --parameters @$(parametersFile) environment=$(environmentName) \
            --result-format FullResourcePayloads

    - task: AzureCLI@2
      displayName: 'Deploy to Production'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "🏭 Deploying to Production environment..."
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file $(bicepFile) \
            --parameters @$(parametersFile) environment=$(environmentName) \
            --name "bicep-$(environmentName)-$(Build.BuildNumber)" \
            --verbose
          
          echo "🎉 Production deployment completed successfully!"

    - task: AzureCLI@2
      displayName: 'Post-Deployment Verification'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "🔍 Verifying production deployment..."
          deploymentStatus=$(az deployment group show \
            --resource-group $(resourceGroupName) \
            --name "bicep-$(environmentName)-$(Build.BuildNumber)" \
            --query properties.provisioningState -o tsv)
          
          if [ "$deploymentStatus" = "Succeeded" ]; then
            echo "✅ Production deployment verified successfully"
            echo "📊 Deployment outputs:"
            az deployment group show \
              --resource-group $(resourceGroupName) \
              --name "bicep-$(environmentName)-$(Build.BuildNumber)" \
              --query properties.outputs
          else
            echo "❌ Production deployment verification failed"
            exit 1
          fi